[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"
  base = "."

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

# 單頁應用路由支援
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
