# netlify.toml

[build]
  command = "npm install --legacy-peer-deps && npm install expo @expo/cli && npx expo export:web"
  publish = "web-build"
  base = "."

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  EXPO_CLI_VERSION = "latest"

# 單頁應用路由支援
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 設定 headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
